<script lang="ts">
  import { theme } from '$lib/theme';
  import { onMount } from 'svelte';

  interface Props {
    card: {
      headword: string;
      definition: string;
      mnemonic?: string;
      etymology?: string;
      tags?: string;
    };
    currentImageUrl?: string;
    onImageGenerated?: (imageUrl: string, prompt: string) => void;
  }

  let { card, currentImageUrl = '', onImageGenerated }: Props = $props();

  // State
  let isGenerating = $state(false);
  let error = $state('');
  let previewUrl = $state(currentImageUrl);
  let generatedPrompt = $state('');
  let usedProvider = $state('');

  // Modal state
  let showModal = $state(false);
  let selectedProvider = $state('runware');
  let selectedStyle = $state('illustrative');

  // Provider options with costs
  const providers = [
    { id: 'runware', name: 'Runware', cost: '~$0.001', desc: 'Cheapest' },
    { id: 'replicate', name: 'Replicate', cost: '~$0.003', desc: 'Balanced' },
    { id: 'laozhang', name: 'Laozhang', cost: '~$0.01', desc: 'Good Quality' },
    { id: 'openai', name: 'OpenAI', cost: '~$0.04', desc: 'Best Quality' }
  ];

  // Style options
  const styles = [
    { id: 'illustrative', name: 'Illustrative' },
    { id: 'comic', name: 'Comic' },
    { id: 'minimal', name: 'Minimal' },
    { id: 'watercolor', name: 'Watercolor' }
  ];

  // Load saved preferences from localStorage
  onMount(() => {
    const savedProvider = localStorage.getItem('vocapp_imagegen_provider');
    const savedStyle = localStorage.getItem('vocapp_imagegen_style');
    if (savedProvider) selectedProvider = savedProvider;
    if (savedStyle) selectedStyle = savedStyle;
  });

  function openModal() {
    showModal = true;
  }

  function closeModal() {
    showModal = false;
  }

  async function handleGenerate() {
    // Save preferences
    localStorage.setItem('vocapp_imagegen_provider', selectedProvider);
    localStorage.setItem('vocapp_imagegen_style', selectedStyle);

    closeModal();
    await generateImage();
  }

  async function generateImage() {
    if (isGenerating) return;

    isGenerating = true;
    error = '';
    usedProvider = '';

    try {
      const response = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          card,
          provider: selectedProvider,
          style: selectedStyle
        })
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.message || 'Failed to generate image');
      }

      const data = await response.json();
      previewUrl = data.imageUrl;
      generatedPrompt = data.prompt;
      usedProvider = data.provider;

      if (onImageGenerated) {
        onImageGenerated(data.imageUrl, data.prompt);
      }
    } catch (e) {
      error = e instanceof Error ? e.message : 'Unknown error';
    } finally {
      isGenerating = false;
    }
  }

  function clearImage() {
    previewUrl = '';
    generatedPrompt = '';
    usedProvider = '';
    if (onImageGenerated) {
      onImageGenerated('', '');
    }
  }
</script>

<div class="image-generator">
  <!-- Preview Area -->
  <div class="preview-container">
    {#if previewUrl}
      <img src={previewUrl} alt={card.headword} class="preview-image" />
      <button
        onclick={clearImage}
        class="clear-btn"
        title="Remove image">
        ✕
      </button>
    {:else}
      <div class="placeholder">
        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
          <circle cx="8.5" cy="8.5" r="1.5"></circle>
          <polyline points="21 15 16 10 5 21"></polyline>
        </svg>
        <span class="placeholder-text">
          {$theme === 'ember' ? 'Visualize this seed' :
           $theme === 'frost' ? 'Crystallize an image' :
           $theme === 'syndicate' ? 'RENDER VISUAL' :
           'Generate image'}
        </span>
      </div>
    {/if}
  </div>

  <!-- Provider Info (shown after generation) -->
  {#if usedProvider && previewUrl}
    <div class="provider-info">
      Generated by: {usedProvider}
    </div>
  {/if}

  <!-- Controls -->
  <div class="controls">
    <button
      onclick={openModal}
      disabled={isGenerating}
      class="generate-btn"
      class:generating={isGenerating}>
      {#if isGenerating}
        <span class="spinner"></span>
        {$theme === 'ember' ? 'Growing...' :
         $theme === 'frost' ? 'Forming...' :
         $theme === 'syndicate' ? 'RENDERING...' :
         'Generating...'}
      {:else}
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M21 12a9 9 0 11-9-9c2.52 0 4.93 1 6.74 2.74L21 8"></path>
          <path d="M21 3v5h-5"></path>
        </svg>
        {$theme === 'ember' ? 'Grow Image' :
         $theme === 'frost' ? 'Form Image' :
         $theme === 'syndicate' ? 'GENERATE' :
         'Generate Image'}
      {/if}
    </button>
  </div>

  <!-- Error Display -->
  {#if error}
    <div class="error-message">
      {error}
    </div>
  {/if}

  <!-- Prompt Preview (collapsed by default) -->
  {#if generatedPrompt}
    <details class="prompt-details">
      <summary class="prompt-summary">View prompt</summary>
      <p class="prompt-text">{generatedPrompt}</p>
    </details>
  {/if}
</div>

<!-- Provider Selection Modal -->
{#if showModal}
  <div class="modal-backdrop" onclick={closeModal}>
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="modal" onclick={(e) => e.stopPropagation()}>
      <div class="modal-header">
        <h3>Generate Image</h3>
        <button class="modal-close" onclick={closeModal}>✕</button>
      </div>

      <div class="modal-body">
        <!-- Provider Selection -->
        <div class="section">
          <label class="section-label">Select Provider:</label>
          <div class="provider-list">
            {#each providers as provider}
              <label class="provider-option">
                <input
                  type="radio"
                  name="provider"
                  value={provider.id}
                  bind:group={selectedProvider}
                />
                <span class="provider-name">{provider.name}</span>
                <span class="provider-desc">({provider.desc})</span>
                <span class="provider-cost">{provider.cost}</span>
              </label>
            {/each}
          </div>
        </div>

        <!-- Style Selection -->
        <div class="section">
          <label class="section-label" for="style-select">Select Style:</label>
          <select id="style-select" class="style-select" bind:value={selectedStyle}>
            {#each styles as style}
              <option value={style.id}>{style.name}</option>
            {/each}
          </select>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn-cancel" onclick={closeModal}>Cancel</button>
        <button class="btn-generate" onclick={handleGenerate}>Generate</button>
      </div>
    </div>
  </div>
{/if}

<style>
  .image-generator {
    margin-top: 1rem;
  }

  .preview-container {
    position: relative;
    width: 100%;
    aspect-ratio: 1;
    max-width: 200px;
    margin: 0 auto 0.5rem;
    border: 2px dashed var(--color-dim);
    border-radius: 1rem;
    overflow: hidden;
    background: var(--color-bg);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .preview-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .clear-btn {
    position: absolute;
    top: 0.5rem;
    right: 0.5rem;
    width: 1.5rem;
    height: 1.5rem;
    border-radius: 50%;
    background: var(--color-danger);
    color: white;
    border: none;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.75rem;
    opacity: 0.8;
    transition: opacity 0.2s;
  }

  .clear-btn:hover {
    opacity: 1;
  }

  .placeholder {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    color: var(--color-dim);
  }

  .placeholder-text {
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
  }

  .provider-info {
    text-align: center;
    font-size: 0.7rem;
    color: var(--color-dim);
    margin-bottom: 0.5rem;
  }

  .controls {
    display: flex;
    justify-content: center;
  }

  .generate-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    padding: 0.75rem 1.5rem;
    background: transparent;
    border: 1px solid var(--color-accent);
    color: var(--color-accent);
    border-radius: 9999px;
    font-family: var(--font-body);
    font-size: 0.875rem;
    cursor: pointer;
    transition: all 0.2s;
  }

  .generate-btn:hover:not(:disabled) {
    background: var(--color-accent);
    color: var(--color-bg);
  }

  .generate-btn:disabled {
    opacity: 0.6;
    cursor: not-allowed;
  }

  .generating {
    animation: pulse 1.5s infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 0.6; }
    50% { opacity: 1; }
  }

  .spinner {
    width: 1rem;
    height: 1rem;
    border: 2px solid transparent;
    border-top-color: currentColor;
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    to { transform: rotate(360deg); }
  }

  .error-message {
    margin-top: 0.75rem;
    padding: 0.5rem;
    background: var(--color-danger);
    color: white;
    font-size: 0.75rem;
    text-align: center;
    border-radius: 0.5rem;
  }

  .prompt-details {
    margin-top: 0.75rem;
  }

  .prompt-summary {
    font-size: 0.75rem;
    color: var(--color-dim);
    cursor: pointer;
    text-align: center;
  }

  .prompt-text {
    margin-top: 0.5rem;
    padding: 0.5rem;
    background: rgba(128, 128, 128, 0.1);
    border-radius: 0.5rem;
    font-size: 0.7rem;
    color: var(--color-dim);
    line-height: 1.4;
  }

  /* Modal Styles */
  .modal-backdrop {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.7);
    backdrop-filter: blur(4px);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
  }

  .modal {
    background: var(--color-panel);
    border: 1px solid var(--color-dim);
    border-radius: 1rem;
    width: 90%;
    max-width: 400px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
  }

  .modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem 1.25rem;
    border-bottom: 1px solid var(--color-dim);
  }

  .modal-header h3 {
    margin: 0;
    font-size: 1.1rem;
    color: var(--color-main);
  }

  .modal-close {
    background: none;
    border: none;
    color: var(--color-dim);
    font-size: 1.25rem;
    cursor: pointer;
    padding: 0;
    line-height: 1;
  }

  .modal-close:hover {
    color: var(--color-accent);
  }

  .modal-body {
    padding: 1.25rem;
  }

  .section {
    margin-bottom: 1.25rem;
  }

  .section:last-child {
    margin-bottom: 0;
  }

  .section-label {
    display: block;
    font-size: 0.8rem;
    text-transform: uppercase;
    letter-spacing: 0.1em;
    color: var(--color-dim);
    margin-bottom: 0.75rem;
  }

  .provider-list {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .provider-option {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.75rem;
    background: var(--color-bg);
    border: 1px solid var(--color-dim);
    border-radius: 0.5rem;
    cursor: pointer;
    transition: all 0.2s;
  }

  .provider-option:hover {
    border-color: var(--color-accent);
  }

  .provider-option:has(input:checked) {
    border-color: var(--color-accent);
    background: rgba(var(--color-accent-rgb), 0.1);
  }

  .provider-option input[type="radio"] {
    accent-color: var(--color-accent);
  }

  .provider-name {
    font-weight: 600;
    color: var(--color-main);
  }

  .provider-desc {
    color: var(--color-dim);
    font-size: 0.8rem;
  }

  .provider-cost {
    margin-left: auto;
    font-size: 0.75rem;
    color: var(--color-success);
    font-family: monospace;
  }

  .style-select {
    width: 100%;
    padding: 0.75rem;
    background: var(--color-bg);
    border: 1px solid var(--color-dim);
    border-radius: 0.5rem;
    color: var(--color-main);
    font-size: 0.9rem;
    cursor: pointer;
  }

  .style-select:focus {
    outline: none;
    border-color: var(--color-accent);
  }

  .modal-footer {
    display: flex;
    gap: 0.75rem;
    padding: 1rem 1.25rem;
    border-top: 1px solid var(--color-dim);
  }

  .btn-cancel, .btn-generate {
    flex: 1;
    padding: 0.75rem;
    border-radius: 0.5rem;
    font-size: 0.9rem;
    cursor: pointer;
    transition: all 0.2s;
  }

  .btn-cancel {
    background: transparent;
    border: 1px solid var(--color-dim);
    color: var(--color-dim);
  }

  .btn-cancel:hover {
    border-color: var(--color-main);
    color: var(--color-main);
  }

  .btn-generate {
    background: var(--color-accent);
    border: 1px solid var(--color-accent);
    color: var(--color-bg);
    font-weight: 600;
  }

  .btn-generate:hover {
    opacity: 0.9;
  }
</style>
