import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import {
  buildImagePrompt,
  canGenerateImage,
  generateImage,
  createRunwareProvider,
  createReplicateProvider,
  createOpenAIProvider,
  type CardData
} from '$lib/imagegen';
import { env } from '$env/dynamic/private';

export const POST: RequestHandler = async ({ request }) => {
  try {
    const body = await request.json();
    const { card, provider: preferredProvider } = body as {
      card: CardData;
      provider?: 'runware' | 'replicate' | 'openai';
    };

    // Validate card data
    if (!card || !card.headword || !card.definition) {
      throw error(400, 'Card data with headword and definition required');
    }

    // Check if card is suitable for image generation
    const validation = canGenerateImage(card);
    if (!validation.valid) {
      throw error(400, validation.reason || 'Card not suitable for image generation');
    }

    // Check if at least one provider is configured
    const hasProvider = env.RUNWARE_API_KEY || env.REPLICATE_API_TOKEN || env.OPENAI_API_KEY;
    if (!hasProvider) {
      throw error(500, 'No image generation providers configured');
    }

    // Build the prompt
    const promptResult = buildImagePrompt(card);

    console.log('Generating image for:', card.headword);
    console.log('Prompt:', promptResult.prompt);

    // Create providers based on preference
    const providers = [];

    // If user specified a provider, try it first
    if (preferredProvider) {
      switch (preferredProvider) {
        case 'runware':
          if (env.RUNWARE_API_KEY) providers.push(createRunwareProvider(env.RUNWARE_API_KEY));
          break;
        case 'replicate':
          if (env.REPLICATE_API_TOKEN) providers.push(createReplicateProvider(env.REPLICATE_API_TOKEN));
          break;
        case 'openai':
          if (env.OPENAI_API_KEY) providers.push(createOpenAIProvider(env.OPENAI_API_KEY));
          break;
      }
    }

    // Add remaining providers as fallbacks (cost-optimized order)
    if (env.RUNWARE_API_KEY && !providers.find(p => p.name === 'runware')) {
      providers.push(createRunwareProvider(env.RUNWARE_API_KEY));
    }
    if (env.REPLICATE_API_TOKEN && !providers.find(p => p.name === 'replicate')) {
      providers.push(createReplicateProvider(env.REPLICATE_API_TOKEN));
    }
    if (env.OPENAI_API_KEY && !providers.find(p => p.name === 'openai')) {
      providers.push(createOpenAIProvider(env.OPENAI_API_KEY));
    }

    // Generate the image
    const result = await generateImage(providers, {
      prompt: promptResult.prompt,
      width: 512,
      height: 512
    });

    if (!result.success) {
      console.error('Image generation failed:', result.error);
      throw error(500, result.error || 'Image generation failed');
    }

    console.log(`Image generated by ${result.provider}:`, result.imageUrl);

    return json({
      imageUrl: result.imageUrl,
      prompt: promptResult.prompt,
      provider: result.provider,
      isAbstract: promptResult.isAbstract
    });

  } catch (e: unknown) {
    console.error('Generate image error:', e);

    if (e && typeof e === 'object' && 'status' in e) {
      throw e;
    }

    const message = e instanceof Error ? e.message : 'Failed to generate image';
    throw error(500, message);
  }
};
