import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import {
  buildImagePrompt,
  canGenerateImage,
  generateImage,
  createRunwareProvider,
  createReplicateProvider,
  createOpenAIProvider,
  createLaozhangProvider,
  type CardData
} from '$lib/imagegen';
import { env } from '$env/dynamic/private';

export const POST: RequestHandler = async ({ request }) => {
  try {
    const body = await request.json();
    const { card, provider: preferredProvider, style } = body as {
      card: CardData;
      provider?: 'runware' | 'replicate' | 'laozhang' | 'openai';
      style?: string;
    };

    // Validate card data
    if (!card || !card.headword || !card.definition) {
      throw error(400, 'Card data with headword and definition required');
    }

    // Check if card is suitable for image generation
    const validation = canGenerateImage(card);
    if (!validation.valid) {
      throw error(400, validation.reason || 'Card not suitable for image generation');
    }

    // Check if at least one provider is configured
    const hasProvider = env.RUNWARE_API_KEY || env.REPLICATE_API_TOKEN || env.LAOZHANG_API_KEY || env.OPENAI_API_KEY;
    if (!hasProvider) {
      throw error(500, 'No image generation providers configured');
    }

    // Build the prompt with optional style
    const promptResult = buildImagePrompt(card);
    let finalPrompt = promptResult.prompt;

    // Apply style modifier if provided
    if (style) {
      const styleModifiers: Record<string, string> = {
        illustrative: 'clean digital illustration style, soft lighting, centered composition',
        comic: 'comic book art style, bold outlines, vibrant colors, dynamic',
        minimal: 'minimalist design, simple shapes, clean lines, white space',
        watercolor: 'watercolor painting style, soft edges, artistic brush strokes'
      };
      if (styleModifiers[style]) {
        finalPrompt = `${promptResult.prompt}. Style: ${styleModifiers[style]}`;
      }
    }

    console.log('Generating image for:', card.headword);
    console.log('Prompt:', finalPrompt);

    // Create providers based on preference
    const providers = [];

    // If user specified a provider, ONLY use that provider (no fallback)
    if (preferredProvider) {
      switch (preferredProvider) {
        case 'runware':
          if (!env.RUNWARE_API_KEY) {
            throw error(400, 'Runware API key not configured. Please select a different provider.');
          }
          providers.push(createRunwareProvider(env.RUNWARE_API_KEY));
          break;
        case 'replicate':
          if (!env.REPLICATE_API_TOKEN) {
            throw error(400, 'Replicate API token not configured. Please select a different provider.');
          }
          providers.push(createReplicateProvider(env.REPLICATE_API_TOKEN));
          break;
        case 'laozhang':
          if (!env.LAOZHANG_API_KEY) {
            throw error(400, 'Laozhang API key not configured. Please select a different provider.');
          }
          providers.push(createLaozhangProvider(env.LAOZHANG_API_KEY, env.LAOZHANG_BASE_URL));
          break;
        case 'openai':
          if (!env.OPENAI_API_KEY) {
            throw error(400, 'OpenAI API key not configured. Please select a different provider.');
          }
          providers.push(createOpenAIProvider(env.OPENAI_API_KEY));
          break;
      }
    } else {
      // No preference - add all configured providers (cost-optimized order)
      if (env.RUNWARE_API_KEY) {
        providers.push(createRunwareProvider(env.RUNWARE_API_KEY));
      }
      if (env.REPLICATE_API_TOKEN) {
        providers.push(createReplicateProvider(env.REPLICATE_API_TOKEN));
      }
      if (env.LAOZHANG_API_KEY) {
        providers.push(createLaozhangProvider(env.LAOZHANG_API_KEY, env.LAOZHANG_BASE_URL));
      }
      if (env.OPENAI_API_KEY) {
        providers.push(createOpenAIProvider(env.OPENAI_API_KEY));
      }
    }

    // Generate the image
    const result = await generateImage(providers, {
      prompt: finalPrompt,
      width: 512,
      height: 512
    });

    if (!result.success) {
      console.error('Image generation failed:', result.error, result.errors);
      return json({
        error: result.error || 'Image generation failed',
        details: result.errors || []
      }, { status: 500 });
    }

    console.log(`Image generated by ${result.provider}:`, result.imageUrl);

    return json({
      imageUrl: result.imageUrl,
      prompt: promptResult.prompt,
      provider: result.provider,
      isAbstract: promptResult.isAbstract
    });

  } catch (e: unknown) {
    console.error('Generate image error:', e);

    if (e && typeof e === 'object' && 'status' in e) {
      throw e;
    }

    const message = e instanceof Error ? e.message : 'Failed to generate image';
    throw error(500, message);
  }
};
